### ISSUE TITLE
Clarification regarding MFV 

### ISSUE THREAD

**Issue by aslyansky-m** [wudongming97/TopoMLP#19]
Hi,
Excellent work, thanks for sharing!
Could you elaborate, this repo contains the code only for TopoMLP or MFV as well?
Because accordingly to [leaderboard](https://paperswithcode.com/sota/3d-lane-detection-on-openlane-v2-2), there is a big difference in performance between these papers. 
The numbers you mentioned in evaluation is consistent with TopoMLP performance.
If not, will the code for MFV be available?

Thanks

**Comment by wudongming97** [comment]
Hi,
I am sorry that we cannot release the code for MFV. This is because the code for competition is so ugly that we release this end-to-end version.

The code for competition is multi-stage training. It uses YOLOv8 for traffic detection. It uses TopoMLP lane head with EVA02 backbone for lane detection.

**Comment by aslyansky-m** [comment]
Ok, I see.
So the main difference between the networks is multi-stage training for MFV and end-to-end in TopoMLP?
The architecture between the 2 papers is similar (uses the code from this repo)?

**Comment by wudongming97** [comment]
Yep. 
Besides the multi-stage training, it is worth noticing that MFV uses YOLOv8 for traffic detection, while TopoMLP uses Deformable DETR head in the end-to-end framework following OpenlaneV2 baseline model.

**Comment by aslyansky-m** [comment]
Great, thank you!
