### ISSUE TITLE
How to implement this experiment of ground-truth topology?

### ISSUE THREAD

**Issue by SuperPengXue** [wudongming97/TopoMLP#8]
![20231212-143649](https://github.com/wudongming97/TopoMLP/assets/46234077/201bcf76-ce38-4c74-ba7f-ee0998b5a785)

Thanks to you awesome work!

**Comment by SuperPengXue** [comment]
now I understand,   Have you ever tried using  ground-truth of lane and traffic element  alone to predict topology of ll and lt?

**Comment by wudongming97** [comment]
Sorry. We have not tried using ground-truth of lane and traffic element alone to predict topology of ll and lt.

**Comment by sugar-fly** [comment]
> now I understand, Have you ever tried using ground-truth of lane and traffic element alone to predict topology of ll and lt?

Hi, I want to continue this discussion. 

Have you conducted this experiment? In the current framework, my experimental findings indicate that ground truth (traffic element and centerline) as input does not significantly enhance topology reasoning. @SuperPengXue 
I'm not sure whether it's due to flaws in my experimental setup. I think the primary focus of the framework is detection, with topology reasoning being treated as an auxiliary task, which makes it difficult to learn robust topology. Is that right? @wudongming97 

Best,

**Comment by wudongming97** [comment]
In this paper, I'd like to express that the topology reasoning is based on the detection performance. It is logical. So I don't think topology reasoning is an auxiliary task.

Using only ground truth (traffic element and centerline) as input to perform topology reasoning seems unreasonable because it lacks a global understanding of lane position or traffic position within an image. Nonetheless, it needs lots of experiments to confirm it.
